### PR TITLE
read remote branches and destroy or add pipelines per each

### PR DESCRIPTION
**Pull request by ilja-peernova**
This change is [Reviewable](https://reviewable.io/reviews/concourse-friends/concourse-builder/13)

### CODE REVIEW

**Comment by ggeorgiev** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[template/sdp/job_branches.go, line 141 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrkVRqGkJ1fU6EZI6Jp:-KrkVRqGkJ1fU6EZI6Jq:b-98k0kw) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/610811e50defcac9aff125bbaf57290aca9039ae/template/sdp/job_branches.go#L141)):*
> ```Go
> 	task := &project.TaskStep{
> 		Platform: model.LinuxPlatform,
> 		Name:     "remove missing pipelines",
> ```

remove not needed pipelines is better

---

*[template/sdp/job_branches.go, line 147 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrkVVMXL-J_BGeWIXMq:-KrkVVMXL-J_BGeWIXMr:b-7ropln) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/610811e50defcac9aff125bbaf57290aca9039ae/template/sdp/job_branches.go#L147)):*
> ```Go
> 				Root: "/bin",
> 			},
> 			RelativePath: "remove_missing_pipelines.sh",
> ```

ditto

---

*[template/sdp/job_branches.go, line 157 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrkVXi31roCCV6vmjw6:-KrkVXi31roCCV6vmjw7:b7zfcw9) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/610811e50defcac9aff125bbaf57290aca9039ae/template/sdp/job_branches.go#L157)):*
> ```Go
> 			"CONCOURSE_PASSWORD": args.Concourse.Password,
> 			"BRANCHES_DIR":       branchesDir.Path(),
> 		},
> ```

we need to add filter, else we are going to drop every other pipeline. Please add PIPELINE_PREFIX and PIPELINE_SUFFIX and remove the pipeline only if it has such prefix and/or suffix - both should be optional

---

*[template/sdp/sdp.go, line 46 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrkVDUYfeTIggILWmDK:-KrkVDUYfeTIggILWmDL:b-ervuw8) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/610811e50defcac9aff125bbaf57290aca9039ae/template/sdp/sdp.go#L46)):*
> ```Go
> 
> 	for _, branch := range branches {
> 		re, err := regexp.Compile("master|release/.*|feature/.*|task/.*")
> ```

use MustCompile and put it outside the for

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13)*

**Comment by ggeorgiev** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[template/sdp/job_branches.go, line 157 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrkVXi31roCCV6vmjw6:-KrkiaakcI1Xh5DNJ2yz:bhptstr) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/610811e50defcac9aff125bbaf57290aca9039ae/template/sdp/job_branches.go#L157)):*
<details><summary><i>Previously, ggeorgiev (George) wrote…</i></summary><blockquote>

we need to add filter, else we are going to drop every other pipeline. Please add PIPELINE_PREFIX and PIPELINE_SUFFIX and remove the pipeline only if it has such prefix and/or suffix - both should be optional
</blockquote></details>

or we should have PIPELINE_REGEX

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13)*

**Comment by ggeorgiev** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[docker/fly/remove_not_needed_pipelines.sh, line 18 at r2](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrlEULUQg0F1Ng00Uio:-KrlEULUQg0F1Ng00Uip:b-one19f) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/b1ebdaa4d126f8cecf9083055c77101236fb8896/docker/fly/remove_not_needed_pipelines.sh#L18)):*
>   if [ -z "$PIPELINE_REGEX"  ]; then
>         name="$PIPELINE_REGEX"
>     
we would like to check if the name of the pipeline matches the regex, this will simply override the name with the regular expression

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13)*

**Comment by ggeorgiev** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13)*

**Comment by ggeorgiev** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[docker/fly/remove_not_needed_pipelines.sh, line 20 at r2](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrlNe7lMucrvB-qEBkx:-KrlNe7lMucrvB-qEBky:b-4xhzyk) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/b1ebdaa4d126f8cecf9083055c77101236fb8896/docker/fly/remove_not_needed_pipelines.sh#L20)):*
> ```Shell
>     fi
> 
>     if echo $branches | grep -w name; then
> ```

please use something like - this does not print on the screeen `if [[ $branches == *" $name "* ]]; then`

---

*[docker/fly/remove_not_needed_pipelines.sh, line 20 at r2](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrlO-JUgUY6-lOWzDMt:-KrlO-JUgUY6-lOWzDMu:b3ej5nm) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/b1ebdaa4d126f8cecf9083055c77101236fb8896/docker/fly/remove_not_needed_pipelines.sh#L20)):*
> ```Shell
>     fi
> 
>     if echo $branches | grep -w name; then
> ```

this should be $name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13)*

**Comment by ggeorgiev** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[docker/fly/remove_not_needed_pipelines.sh, line 16 at r2](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrlOFPKN9w3vS0erNVx:-KrlOFPKN9w3vS0erNVy:bttd0r8) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/b1ebdaa4d126f8cecf9083055c77101236fb8896/docker/fly/remove_not_needed_pipelines.sh#L16)):*
> ```Shell
>     name=$(echo $yml | cut -f 1 -d '.')
> 
>     if [ -z "$PIPELINE_REGEX"  ]; then
> ```

I think you can use `[[ $name =~ $PIPELINE_REGEX ]]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13)*

**Comment by ggeorgiev** [comment]
Review status: 3 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[docker/git/obtain_branches.sh, line 28 at r3](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrpLPGqdxqnKb9mG0O1:-KrpLPGqdxqnKb9mG0O2:b8yl39p) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/ae53415459e7b37320c105069cc28fe794a954e3/docker/git/obtain_branches.sh#L28)):*
> git branch -r | \
>   grep -v ">" | \
>   while read rbranch
>      do echo $rbranch | rev | cut -d/ -f1 | rev
>   done
this is not correct

if we have `origin/release/foo` we want `release/foo` not just `foo`
also we still want `master` in just not in this : `origin/HEAD -> origin/master` form

what about `git branch -r | sed 's/.*-\>//g' | sed 's/^ *origin\///g'`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13)*

**Comment by ilja-peernova** [comment]
+@ggeorgiev 

---

Review status: 1 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[docker/fly/remove_not_needed_pipelines.sh, line 16 at r2](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrlOFPKN9w3vS0erNVx:-KrpoOxfMdzRfvpD5B8_:b-896fix) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/b1ebdaa4d126f8cecf9083055c77101236fb8896/docker/fly/remove_not_needed_pipelines.sh#L16)):*
<details><summary><i>Previously, ggeorgiev (George) wrote…</i></summary><blockquote>

I think you can use `[[ $name =~ $PIPELINE_REGEX ]]`
</blockquote></details>

Done.

---

*[docker/fly/remove_not_needed_pipelines.sh, line 18 at r2](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrlEULUQg0F1Ng00Uio:-KrpoOgU-rbl6Hj5fBXo:b-896fix) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/b1ebdaa4d126f8cecf9083055c77101236fb8896/docker/fly/remove_not_needed_pipelines.sh#L18)):*
<details><summary><i>Previously, ggeorgiev (George) wrote…</i></summary><blockquote>

>   if [ -z "$PIPELINE_REGEX"  ]; then
>         name="$PIPELINE_REGEX"
>     
we would like to check if the name of the pipeline matches the regex, this will simply override the name with the regular expression
</blockquote></details>

Done.

---

*[docker/fly/remove_not_needed_pipelines.sh, line 20 at r2](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrlNe7lMucrvB-qEBkx:-KrpoOEE126xkih6cper:b-896fix) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/b1ebdaa4d126f8cecf9083055c77101236fb8896/docker/fly/remove_not_needed_pipelines.sh#L20)):*
<details><summary><i>Previously, ggeorgiev (George) wrote…</i></summary><blockquote>

please use something like - this does not print on the screeen `if [[ $branches == *" $name "* ]]; then`
</blockquote></details>

Done.

---

*[docker/fly/remove_not_needed_pipelines.sh, line 20 at r2](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrlO-JUgUY6-lOWzDMt:-KrpoNxX2yDiePhFYEGX:b-896fix) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/b1ebdaa4d126f8cecf9083055c77101236fb8896/docker/fly/remove_not_needed_pipelines.sh#L20)):*
<details><summary><i>Previously, ggeorgiev (George) wrote…</i></summary><blockquote>

this should be $name
</blockquote></details>

Done.

---

*[docker/fly/remove_not_needed_pipelines.sh, line 15 at r5](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrqTFzG5kQ3EmClHgpW:-KrqTFzG5kQ3EmClHgpX:bvyso9c) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/387d957cc879853f7eba345798071e819c42bcbc/docker/fly/remove_not_needed_pipelines.sh#L15)):*
> ```Shell
> PIPELINE_FILES=$(for yml in *; do name=$(echo $yml | cut -f 1 -d '.');done)
> 
> if [ ! -z "$PIPELINE_REGEX" ]; then
> ```

@ggeorgiev please see updated version

---

*[docker/git/obtain_branches.sh, line 28 at r3](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrpLPGqdxqnKb9mG0O1:-KrpoRWNRqSe4GwBIBBU:b-896fix) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/ae53415459e7b37320c105069cc28fe794a954e3/docker/git/obtain_branches.sh#L28)):*
<details><summary><i>Previously, ggeorgiev (George) wrote…</i></summary><blockquote>

> git branch -r | \
>   grep -v ">" | \
>   while read rbranch
>      do echo $rbranch | rev | cut -d/ -f1 | rev
>   done
this is not correct

if we have `origin/release/foo` we want `release/foo` not just `foo`
also we still want `master` in just not in this : `origin/HEAD -> origin/master` form

what about `git branch -r | sed 's/.*-\>//g' | sed 's/^ *origin\///g'`



</blockquote></details>

Done.

---

*[template/sdp/job_branches.go, line 141 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrkVRqGkJ1fU6EZI6Jp:-Krkh-_2fRS4zPuULQ8L:b-896fix) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/610811e50defcac9aff125bbaf57290aca9039ae/template/sdp/job_branches.go#L141)):*
<details><summary><i>Previously, ggeorgiev (George) wrote…</i></summary><blockquote>

remove not needed pipelines is better
</blockquote></details>

Done.

---

*[template/sdp/job_branches.go, line 147 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrkVVMXL-J_BGeWIXMq:-Krkh0_BsbqpPyz-HotF:b-896fix) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/610811e50defcac9aff125bbaf57290aca9039ae/template/sdp/job_branches.go#L147)):*
<details><summary><i>Previously, ggeorgiev (George) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[template/sdp/job_branches.go, line 156 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrkUUyCyCKgX_ClM-UM:-KrkUUyDe-qB1hL_fLrQ:b-enal0b) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/610811e50defcac9aff125bbaf57290aca9039ae/template/sdp/job_branches.go#L156)):*
> ```Go
> 			"CONCOURSE_USER":     args.Concourse.User,
> 			"CONCOURSE_PASSWORD": args.Concourse.Password,
> 			"BRANCHES_DIR":       branchesDir.Path(),
> ```

I'm not sure that the directory will be available here physically 

---

*[template/sdp/job_branches.go, line 157 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrkVXi31roCCV6vmjw6:-KrkqbUk5rBT3cm_oEkD:b-896fix) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/610811e50defcac9aff125bbaf57290aca9039ae/template/sdp/job_branches.go#L157)):*
<details><summary><i>Previously, ggeorgiev (George) wrote…</i></summary><blockquote>

or we should have PIPELINE_REGEX
</blockquote></details>

Done.

---

*[template/sdp/sdp.go, line 46 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrkVDUYfeTIggILWmDK:-KrkgwJfxfay3uxsZW7F:b-896fix) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/610811e50defcac9aff125bbaf57290aca9039ae/template/sdp/sdp.go#L46)):*
<details><summary><i>Previously, ggeorgiev (George) wrote…</i></summary><blockquote>

use MustCompile and put it outside the for
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-:-KrkUcv87RiqjnFSGQ8t:b-uq94ht)*

**Comment by ggeorgiev** [comment]
Review status: 1 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[docker/fly/remove_not_needed_pipelines.sh, line 15 at r5](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrqTFzG5kQ3EmClHgpW:-KrqTOpWUibe9Yb_OmsU:bdibbry) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/387d957cc879853f7eba345798071e819c42bcbc/docker/fly/remove_not_needed_pipelines.sh#L15)):*
<details><summary><i>Previously, ilja-peernova wrote…</i></summary><blockquote>

@ggeorgiev please see updated version
</blockquote></details>

My point of having this in the loop is that if PIPELINE_REGEX is not specify we assume any

which you actually do with 

if [ -z "$PIPELINE_REGEX ]; then
    PIPELINE_REGEX=.*
fi

and then the the loop at this level

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13)*

**Comment by ggeorgiev** [comment]
Reviewed 1 of 4 files at r2, 1 of 3 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[docker/fly/remove_not_needed_pipelines.sh, line 20 at r2](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrlNe7lMucrvB-qEBkx:-KrqTyoQt0_jq9cxP4t3:bfz0ilp) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/b1ebdaa4d126f8cecf9083055c77101236fb8896/docker/fly/remove_not_needed_pipelines.sh#L20)):*
<details><summary><i>Previously, ilja-peernova wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you still use grep

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13)*

**Comment by ggeorgiev** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[template/sdp/job_branches.go, line 156 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrkUUyCyCKgX_ClM-UM:-KrqUob7bBYhmzLcPi-i:bfhp2p3) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/610811e50defcac9aff125bbaf57290aca9039ae/template/sdp/job_branches.go#L156)):*
> &library.Location{
> 				Volume: pipelinesDir,
> 			},
you need to pass it like that:

&library.Location{
				Volume: pipelinesDir,
			},
else it will not know to input it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13)*

**Comment by ggeorgiev** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[template/sdp/job_branches.go, line 156 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13#-KrkUUyCyCKgX_ClM-UM:-KrqV-Q_HT5l32XUuCY_:byuecgc) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/610811e50defcac9aff125bbaf57290aca9039ae/template/sdp/job_branches.go#L156)):*
<details><summary><i>Previously, ggeorgiev (George) wrote…</i></summary><blockquote>

> &library.Location{
> 				Volume: pipelinesDir,
> 			},
you need to pass it like that:

&library.Location{
				Volume: pipelinesDir,
			},
else it will not know to input it
</blockquote></details>

sorry I mean branches

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13)*

**Comment by ggeorgiev** [comment]
Reviewed 1 of 4 files at r2, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/13)*

**Pull request merged**
