### PR TITLE
Added job_aws_image to create aws docker image

### PR DESCRIPTION
**Pull request by SuryaBommadevara**
This change is [Reviewable](https://reviewable.io/reviews/concourse-friends/concourse-builder/61)

### CODE REVIEW

**Comment by SuryaBommadevara** [comment]
@ggeorgiev

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/61#-:-KwqKFnSxidIf3Qvk_VG:b-t1aaba)*

**Comment by ggeorgiev** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docker/aws/clean-untagged-ecr-images.sh, line 8 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/61#-KwqWq-nMJEoIeCajLWs:-KwqWq-nMJEoIeCajLWt:b-sp85cn) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/0dedb486eb4b0f06c0e78f385a1802fbec7fa6fc/docker/aws/clean-untagged-ecr-images.sh#L8)):*
> IFS= read -r line
> do
> IMAGES=$(aws ecr list-images --repository-name $line --filter tagStatus=UNTAGGED --query 'imageIds[?type(imageTag)!=`string`].[imageDigest]' --output text)
> echo "Deleting all images with no tag from $line..."
> for DIGEST in ${IMAGES[*]}
> do
> aws ecr batch-delete-image  --repository-name $line --image-ids imageDigest=$DIGEST
> done
> done <<<
please indent the code that is inside logical blocks

---

*[docker/aws/configure.sh, line 5 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/61#-KwqWhIW69MjHwOA0ZKe:-KwqWhIW69MjHwOA0ZKf:b-oclspy) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/0dedb486eb4b0f06c0e78f385a1802fbec7fa6fc/docker/aws/configure.sh#L5)):*
> ```Shell
> set +e
> 
> aws configure set aws_access_key_id $bot_aws_access_id
> ```

please all uppercase no need of bot_ prefix

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/61)*

**Comment by SuryaBommadevara** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[docker/aws/clean-untagged-ecr-images.sh, line 8 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/61#-KwqWq-nMJEoIeCajLWs:-Kwqio1yr4W7TJ5qpBZQ:b-896fix) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/0dedb486eb4b0f06c0e78f385a1802fbec7fa6fc/docker/aws/clean-untagged-ecr-images.sh#L8)):*
<details><summary><i>Previously, ggeorgiev (George) wrote…</i></summary><blockquote>

> IFS= read -r line
> do
> IMAGES=$(aws ecr list-images --repository-name $line --filter tagStatus=UNTAGGED --query 'imageIds[?type(imageTag)!=`string`].[imageDigest]' --output text)
> echo "Deleting all images with no tag from $line..."
> for DIGEST in ${IMAGES[*]}
> do
> aws ecr batch-delete-image  --repository-name $line --image-ids imageDigest=$DIGEST
> done
> done <<<
please indent the code that is inside logical blocks
</blockquote></details>

Done.

---

*[docker/aws/configure.sh, line 5 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/61#-KwqWhIW69MjHwOA0ZKe:-KwqinW5VeNSElCRUMPs:b-896fix) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/0dedb486eb4b0f06c0e78f385a1802fbec7fa6fc/docker/aws/configure.sh#L5)):*
<details><summary><i>Previously, ggeorgiev (George) wrote…</i></summary><blockquote>

please all uppercase no need of bot_ prefix
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/61)*

**Comment by SuryaBommadevara** [comment]
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[docker/aws/clean-untagged-ecr-images.sh, line 8 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/61#-KwqWq-nMJEoIeCajLWs:-Kwqk24ko0aaSAApC_De:b6nvw9) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/0dedb486eb4b0f06c0e78f385a1802fbec7fa6fc/docker/aws/clean-untagged-ecr-images.sh#L8)):*
<details><summary><i>Previously, SuryaBommadevara wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Updated indentation in script as instructed. @ggeorgiev

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/61)*

**Comment by ggeorgiev** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/61)*

**Pull request merged**
