### PR TITLE
Add custom resource type support; Use gitmulti for the target

### PR DESCRIPTION
**Pull request by ggeorgiev**
This change is [Reviewable](https://reviewable.io/reviews/concourse-friends/concourse-builder/14)

### CODE REVIEW

**Comment by ggeorgiev** [comment]
+@andrewatpn +@ilja-peernova 

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/14#-:-KrmQi8d4D4TFaWemG7c:btiprj0)*

**Comment by andrewAtpn** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[library/git_repo.go, line 7 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/14#-KrmURUAcZDmyl1X2xLZ:-KrmURUAcZDmyl1X2xL_:baj22mi) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/fcc2b26f0e344f3ad11397e2e26be129a7218ae8/library/git_repo.go#L7)):*
> ```Go
> 	URI string `yaml:",omitempty"`
> 
> 	// Private key the has access to the repo
> ```

replace 'the has' with 'allows'  or something similar

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/14)*

**Comment by ggeorgiev** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[library/git_repo.go, line 7 at r1](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/14#-KrmURUAcZDmyl1X2xLZ:-KrmXq9fv3jK577Aw6ZT:b-896fix) ([raw file](https://github.com/concourse-friends/concourse-builder/blob/fcc2b26f0e344f3ad11397e2e26be129a7218ae8/library/git_repo.go#L7)):*
<details><summary><i>Previously, andrewAtpn wrote…</i></summary><blockquote>

replace 'the has' with 'allows'  or something similar
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/14)*

**Comment by andrewAtpn** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/concourse-friends/concourse-builder/14)*

**Pull request merged**
